blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Reporting
    url: https://github.com/lock14/doom-configs/security/policy
    about: Please report security vulnerabilities privately according to our security policy.
